drop table if exists answers;
drop table if exists doctor_patient;
drop table if exists doctors;
drop table if exists patients;
drop table if exists question_notes;
drop table if exists questions;
drop table if exists tests;
drop table if exists users;
create table answers (score integer not null, version integer, answer_id varchar(36) not null, question_id varchar(36) not null, test_id varchar(36) not null, video_link varchar(255), primary key (answer_id)) engine=InnoDB;
create table doctor_patient (doctor_id varchar(36) not null, patient_id varchar(36) not null, primary key (doctor_id, patient_id)) engine=InnoDB;
create table doctors (version integer, user_user_id varchar(36) not null, license_number char(50) not null, specialty varchar(100) not null, primary key (user_user_id)) engine=InnoDB;
create table patients (date_of_birth date, version integer, user_user_id varchar(36) not null, medical_history TEXT(5000), primary key (user_user_id)) engine=InnoDB;
create table question_notes (version integer, question_id varchar(36) not null, question_note_id varchar(36) not null, test_id varchar(36) not null, note TEXT(500), primary key (question_note_id)) engine=InnoDB;
create table questions (version integer, question_id varchar(36) not null, test_id varchar(36) not null, primary key (question_id)) engine=InnoDB;
create table tests (total_cmas_score integer, version integer, assigned_date datetime(6), completed_date datetime(6), doctor_id varchar(36) not null, patient_id varchar(36) not null, test_id varchar(36) not null, status enum ('ASSIGNED','COMPLETED') not null, primary key (test_id)) engine=InnoDB;
create table users (version integer, created_date datetime(6), update_date datetime(6), user_id varchar(36) not null, username varchar(50) not null, password_hash varchar(64) not null, email varchar(255) not null, first_name varchar(255) not null, last_name varchar(255) not null, phone_number varchar(255), role varchar(255) not null, primary key (user_id)) engine=InnoDB;
alter table answers add constraint UKennkg4xsvie7daas69sdewc71 unique (test_id, question_id);
alter table doctors add constraint UK1xu5x0jae737xae254t4rgcd1 unique (license_number);
alter table question_notes add constraint UKakvpowgj6r77gjs791xiweo7p unique (test_id, question_id);
alter table answers add constraint FK3erw1a3t0r78st8ty27x6v3g1 foreign key (question_id) references questions (question_id);
alter table answers add constraint FK8xwf2faiahwf07fa6e9sffuo7 foreign key (test_id) references tests (test_id);
alter table doctor_patient add constraint FKjda75ix2tcxtuemg6v1n0f453 foreign key (patient_id) references patients (user_user_id);
alter table doctor_patient add constraint FK9gfear64wbhtnnxgqqj5q94x6 foreign key (doctor_id) references doctors (user_user_id);
alter table doctors add constraint FK2corffclxsrn27i63f66e2ay6 foreign key (user_user_id) references users (user_id);
alter table patients add constraint FKhws2od4xnom0x3h50gh29yyhk foreign key (user_user_id) references users (user_id);
alter table question_notes add constraint FK75e56vknpfx2sjwyddqpe7tlj foreign key (question_id) references questions (question_id);
alter table question_notes add constraint FK2fu6dq614xetbcjcc59nrflbl foreign key (test_id) references tests (test_id);
alter table questions add constraint FKoc6xkgj16nhyyes4ath9dyxxw foreign key (test_id) references tests (test_id);
alter table tests add constraint FKt9hbara22bqu6be8dhw5jb2id foreign key (doctor_id) references doctors (user_user_id);
alter table tests add constraint FK1qkgkri4w0j500etitw3brbrr foreign key (patient_id) references patients (user_user_id);