drop table if exists answers;
drop table if exists doctor_patient;
drop table if exists doctors;
drop table if exists patients;
drop table if exists question_notes;
drop table if exists questions;
drop table if exists tests;
drop table if exists users;
create table answers (version integer, id varchar(36) not null, question_id varchar(36) not null, test_assignment_id varchar(36) not null, response TEXT(500) not null, video_link varchar(255), primary key (id)) engine=InnoDB;
create table doctor_patient (doctor_id varchar(36) not null, patient_id varchar(36) not null, primary key (doctor_id, patient_id)) engine=InnoDB;
create table doctors (version integer, user_id varchar(36) not null, license_number char(50) not null, specialty varchar(100) not null, primary key (user_id)) engine=InnoDB;
create table patients (date_of_birth date, version integer, user_id varchar(36) not null, medical_history TEXT(5000), primary key (user_id)) engine=InnoDB;
create table question_notes (version integer, id varchar(36) not null, question_id varchar(36) not null, test_id varchar(36) not null, note TEXT(500), primary key (id)) engine=InnoDB;
create table questions (version integer, id varchar(36) not null, test_id varchar(36) not null, primary key (id)) engine=InnoDB;
create table tests (version integer, assigned_date datetime(6), completed_date datetime(6), doctor_id varchar(36) not null, id varchar(36) not null, patient_id varchar(36) not null, status enum ('ASSIGNED','COMPLETED') not null, primary key (id)) engine=InnoDB;
create table users (version integer, created_date datetime(6), update_date datetime(6), id varchar(36) not null, username varchar(50) not null, password_hash varchar(64) not null, email varchar(255) not null, first_name varchar(255) not null, last_name varchar(255) not null, phone_number varchar(255), role varchar(255) not null, primary key (id)) engine=InnoDB;
alter table answers add constraint UKbr7n08cdv3fa2ux3ebhkd6w4g unique (test_assignment_id, question_id);
alter table doctors add constraint UK1xu5x0jae737xae254t4rgcd1 unique (license_number);
alter table question_notes add constraint UKdxk7sbp2efq657d63kmcc59qs unique (test_assignment_id, question_id);
alter table answers add constraint FK3erw1a3t0r78st8ty27x6v3g1 foreign key (question_id) references questions (id);
alter table answers add constraint FK3qyd18j8aqbr88x2ho2jv0h2f foreign key (test_assignment_id) references tests (id);
alter table doctor_patient add constraint FKjda75ix2tcxtuemg6v1n0f453 foreign key (patient_id) references patients (user_id);
alter table doctor_patient add constraint FK9gfear64wbhtnnxgqqj5q94x6 foreign key (doctor_id) references doctors (user_id);
alter table doctors add constraint FKe9pf5qtxxkdyrwibaevo9frtk foreign key (user_id) references users (id);
alter table patients add constraint FKuwca24wcd1tg6pjex8lmc0y7 foreign key (user_id) references users (id);
alter table question_notes add constraint FK75e56vknpfx2sjwyddqpe7tlj foreign key (question_id) references questions (id);
alter table question_notes add constraint FK2fu6dq614xetbcjcc59nrflbl foreign key (test_id) references tests (id);
alter table questions add constraint FKoc6xkgj16nhyyes4ath9dyxxw foreign key (test_id) references tests (id);
alter table tests add constraint FKt9hbara22bqu6be8dhw5jb2id foreign key (doctor_id) references doctors (user_id);
alter table tests add constraint FK1qkgkri4w0j500etitw3brbrr foreign key (patient_id) references patients (user_id);
